version: '3.9'
services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./sql_test_init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -U postgres

  university_app:
    container_name: university_app
    build: .
    ports:
      - 8000:8000
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=postgres
    command: ['pytest', 'tests/']
    volumes:
      - ./tests:/code/tests
    depends_on:
      - postgres
